//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package wholepkg

import (
	bits "math/bits"
	sync "sync"
	unsafe "unsafe"

	otherpkg "github.com/ravinggo/tools/deepcopy-gen/output_tests/otherpkg"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ManualSlice) DeepCopyInto(out *ManualSlice) {
	{
		in := &in
		*out = in.DeepCopy()
		return
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualStruct) DeepCopyInto(out *ManualStruct) {
	*out = in.DeepCopy()
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualStructAlias) DeepCopyInto(out *ManualStructAlias) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualStructAlias.
func (in *ManualStructAlias) DeepCopy() *ManualStructAlias {
	if in == nil {
		return nil
	}
	out := ManualStructAliasPool.Get().(*ManualStructAlias)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *ManualStructAlias) Reset() {
	if in == nil {
		return
	}
	*in = ManualStructAlias{}
	ManualStructAliasPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *ManualStructAlias) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *ManualStructAlias) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = ManualStructAlias{}
	ManualStructAliasPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructB) DeepCopyInto(out *StructB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructB.
func (in *StructB) DeepCopy() *StructB {
	if in == nil {
		return nil
	}
	out := StructBPool.Get().(*StructB)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructB) Reset() {
	if in == nil {
		return
	}
	*in = StructB{}
	StructBPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructB) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructB) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructB{}
	StructBPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedInt) DeepCopyInto(out *StructEmbedInt) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedInt.
func (in *StructEmbedInt) DeepCopy() *StructEmbedInt {
	if in == nil {
		return nil
	}
	out := StructEmbedIntPool.Get().(*StructEmbedInt)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructEmbedInt) Reset() {
	if in == nil {
		return
	}
	*in = StructEmbedInt{}
	StructEmbedIntPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructEmbedInt) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructEmbedInt) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructEmbedInt{}
	StructEmbedIntPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedManualStruct) DeepCopyInto(out *StructEmbedManualStruct) {
	*out = *in
	out.ManualStruct = in.ManualStruct.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedManualStruct.
func (in *StructEmbedManualStruct) DeepCopy() *StructEmbedManualStruct {
	if in == nil {
		return nil
	}
	out := StructEmbedManualStructPool.Get().(*StructEmbedManualStruct)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructEmbedManualStruct) Reset() {
	if in == nil {
		return
	}
	in.ManualStruct.Reset()
	*in = StructEmbedManualStruct{}
	StructEmbedManualStructPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructEmbedManualStruct) ResetNoSelf() {
	if in == nil {
		return
	}
	in.ManualStruct.Reset()
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructEmbedManualStruct) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructEmbedManualStruct{}
	StructEmbedManualStructPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedPointer) DeepCopyInto(out *StructEmbedPointer) {
	*out = *in
	if in.int != nil {
		in, out := &in.int, &out.int
		*out = intp_Pool.Get().(*int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedPointer.
func (in *StructEmbedPointer) DeepCopy() *StructEmbedPointer {
	if in == nil {
		return nil
	}
	out := StructEmbedPointerPool.Get().(*StructEmbedPointer)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructEmbedPointer) Reset() {
	if in == nil {
		return
	}
	if in.int != nil {
		in := &in.int
		x := (*int)(*in)
		intp_Pool.Put(x)
	}
	*in = StructEmbedPointer{}
	StructEmbedPointerPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructEmbedPointer) ResetNoSelf() {
	if in == nil {
		return
	}
	if in.int != nil {
		in := &in.int
		x := (*int)(*in)
		intp_Pool.Put(x)
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructEmbedPointer) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructEmbedPointer{}
	StructEmbedPointerPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedStructPrimitivePointers) DeepCopyInto(out *StructEmbedStructPrimitivePointers) {
	*out = *in
	in.StructPrimitivePointers.DeepCopyInto(&out.StructPrimitivePointers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedStructPrimitivePointers.
func (in *StructEmbedStructPrimitivePointers) DeepCopy() *StructEmbedStructPrimitivePointers {
	if in == nil {
		return nil
	}
	out := StructEmbedStructPrimitivePointersPool.Get().(*StructEmbedStructPrimitivePointers)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructEmbedStructPrimitivePointers) Reset() {
	if in == nil {
		return
	}
	in.StructPrimitivePointers.ResetNoSelf()
	*in = StructEmbedStructPrimitivePointers{}
	StructEmbedStructPrimitivePointersPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructEmbedStructPrimitivePointers) ResetNoSelf() {
	if in == nil {
		return
	}
	in.StructPrimitivePointers.ResetNoSelf()
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructEmbedStructPrimitivePointers) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructEmbedStructPrimitivePointers{}
	StructEmbedStructPrimitivePointersPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedStructPrimitives) DeepCopyInto(out *StructEmbedStructPrimitives) {
	*out = *in
	out.StructPrimitives = in.StructPrimitives
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedStructPrimitives.
func (in *StructEmbedStructPrimitives) DeepCopy() *StructEmbedStructPrimitives {
	if in == nil {
		return nil
	}
	out := StructEmbedStructPrimitivesPool.Get().(*StructEmbedStructPrimitives)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructEmbedStructPrimitives) Reset() {
	if in == nil {
		return
	}
	*in = StructEmbedStructPrimitives{}
	StructEmbedStructPrimitivesPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructEmbedStructPrimitives) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructEmbedStructPrimitives) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructEmbedStructPrimitives{}
	StructEmbedStructPrimitivesPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedStructSlices) DeepCopyInto(out *StructEmbedStructSlices) {
	*out = *in
	in.StructSlices.DeepCopyInto(&out.StructSlices)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedStructSlices.
func (in *StructEmbedStructSlices) DeepCopy() *StructEmbedStructSlices {
	if in == nil {
		return nil
	}
	out := StructEmbedStructSlicesPool.Get().(*StructEmbedStructSlices)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructEmbedStructSlices) Reset() {
	if in == nil {
		return
	}
	in.StructSlices.ResetNoSelf()
	*in = StructEmbedStructSlices{}
	StructEmbedStructSlicesPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructEmbedStructSlices) ResetNoSelf() {
	if in == nil {
		return
	}
	in.StructSlices.ResetNoSelf()
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructEmbedStructSlices) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructEmbedStructSlices{}
	StructEmbedStructSlicesPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmpty) DeepCopyInto(out *StructEmpty) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmpty.
func (in *StructEmpty) DeepCopy() *StructEmpty {
	if in == nil {
		return nil
	}
	out := StructEmptyPool.Get().(*StructEmpty)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructEmpty) Reset() {
	if in == nil {
		return
	}
	*in = StructEmpty{}
	StructEmptyPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructEmpty) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructEmpty) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructEmpty{}
	StructEmptyPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEverything) DeepCopyInto(out *StructEverything) {
	*out = *in
	out.StructField = in.StructField
	out.EmptyStructField = in.EmptyStructField
	out.ManualStructField = in.ManualStructField.DeepCopy()
	out.ManualStructAliasField = in.ManualStructAliasField
	if in.BoolPtrField != nil {
		in, out := &in.BoolPtrField, &out.BoolPtrField
		*out = boolp_Pool.Get().(*bool)
		**out = **in
	}
	if in.IntPtrField != nil {
		in, out := &in.IntPtrField, &out.IntPtrField
		*out = intp_Pool.Get().(*int)
		**out = **in
	}
	if in.StringPtrField != nil {
		in, out := &in.StringPtrField, &out.StringPtrField
		*out = stringp_Pool.Get().(*string)
		**out = **in
	}
	if in.FloatPtrField != nil {
		in, out := &in.FloatPtrField, &out.FloatPtrField
		*out = float64p_Pool.Get().(*float64)
		**out = **in
	}
	in.PrimitivePointersField.DeepCopyInto(&out.PrimitivePointersField)
	if in.ManualStructPtrField != nil {
		in, out := &in.ManualStructPtrField, &out.ManualStructPtrField
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ManualStructAliasPtrField != nil {
		in, out := &in.ManualStructAliasPtrField, &out.ManualStructAliasPtrField
		*out = ManualStructAliasp_Pool.Get().(*ManualStructAlias)
		**out = **in
	}
	if in.SliceBoolField != nil {
		in, out := &in.SliceBoolField, &out.SliceBoolField
		*out = s_boolSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceByteField != nil {
		in, out := &in.SliceByteField, &out.SliceByteField
		*out = s_byteSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceIntField != nil {
		in, out := &in.SliceIntField, &out.SliceIntField
		*out = s_intSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStringField != nil {
		in, out := &in.SliceStringField, &out.SliceStringField
		*out = s_stringSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceFloatField != nil {
		in, out := &in.SliceFloatField, &out.SliceFloatField
		*out = s_float64SPool.Get(len(*in))
		copy(*out, *in)
	}
	in.SlicesField.DeepCopyInto(&out.SlicesField)
	if in.SliceManualStructField != nil {
		in, out := &in.SliceManualStructField, &out.SliceManualStructField
		*out = s_ManualStructSPool.Get(len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ManualSliceField = in.ManualSliceField.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEverything.
func (in *StructEverything) DeepCopy() *StructEverything {
	if in == nil {
		return nil
	}
	out := StructEverythingPool.Get().(*StructEverything)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructEverything) Reset() {
	if in == nil {
		return
	}
	in.ManualStructField.Reset()
	if in.BoolPtrField != nil {
		in := &in.BoolPtrField
		x := (*bool)(*in)
		boolp_Pool.Put(x)
	}
	if in.IntPtrField != nil {
		in := &in.IntPtrField
		x := (*int)(*in)
		intp_Pool.Put(x)
	}
	if in.StringPtrField != nil {
		in := &in.StringPtrField
		x := (*string)(*in)
		stringp_Pool.Put(x)
	}
	if in.FloatPtrField != nil {
		in := &in.FloatPtrField
		x := (*float64)(*in)
		float64p_Pool.Put(x)
	}
	in.PrimitivePointersField.ResetNoSelf()
	if in.ManualStructPtrField != nil {
		in.ManualStructPtrField.Reset()
	}
	if in.ManualStructAliasPtrField != nil {
		in := &in.ManualStructAliasPtrField
		x := (*ManualStructAlias)(*in)
		ManualStructAliasp_Pool.Put(x)
	}
	if in.SliceBoolField != nil {
		in := &in.SliceBoolField
		s_boolSPool.Put(*in)
	}
	if in.SliceByteField != nil {
		in := &in.SliceByteField
		s_byteSPool.Put(*in)
	}
	if in.SliceIntField != nil {
		in := &in.SliceIntField
		s_intSPool.Put(*in)
	}
	if in.SliceStringField != nil {
		in := &in.SliceStringField
		s_stringSPool.Put(*in)
	}
	if in.SliceFloatField != nil {
		in := &in.SliceFloatField
		s_float64SPool.Put(*in)
	}
	in.SlicesField.ResetNoSelf()
	if in.SliceManualStructField != nil {
		in := &in.SliceManualStructField
		for i := range *in {
			(*in)[i].Reset()
		}
		s_ManualStructSPool.Put(*in)
	}
	in.ManualSliceField.Reset()
	*in = StructEverything{}
	StructEverythingPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructEverything) ResetNoSelf() {
	if in == nil {
		return
	}
	in.ManualStructField.Reset()
	if in.BoolPtrField != nil {
		in := &in.BoolPtrField
		x := (*bool)(*in)
		boolp_Pool.Put(x)
	}
	if in.IntPtrField != nil {
		in := &in.IntPtrField
		x := (*int)(*in)
		intp_Pool.Put(x)
	}
	if in.StringPtrField != nil {
		in := &in.StringPtrField
		x := (*string)(*in)
		stringp_Pool.Put(x)
	}
	if in.FloatPtrField != nil {
		in := &in.FloatPtrField
		x := (*float64)(*in)
		float64p_Pool.Put(x)
	}
	in.PrimitivePointersField.ResetNoSelf()
	if in.ManualStructPtrField != nil {
		in.ManualStructPtrField.Reset()
	}
	if in.ManualStructAliasPtrField != nil {
		in := &in.ManualStructAliasPtrField
		x := (*ManualStructAlias)(*in)
		ManualStructAliasp_Pool.Put(x)
	}
	if in.SliceBoolField != nil {
		in := &in.SliceBoolField
		s_boolSPool.Put(*in)
	}
	if in.SliceByteField != nil {
		in := &in.SliceByteField
		s_byteSPool.Put(*in)
	}
	if in.SliceIntField != nil {
		in := &in.SliceIntField
		s_intSPool.Put(*in)
	}
	if in.SliceStringField != nil {
		in := &in.SliceStringField
		s_stringSPool.Put(*in)
	}
	if in.SliceFloatField != nil {
		in := &in.SliceFloatField
		s_float64SPool.Put(*in)
	}
	in.SlicesField.ResetNoSelf()
	if in.SliceManualStructField != nil {
		in := &in.SliceManualStructField
		for i := range *in {
			(*in)[i].Reset()
		}
		s_ManualStructSPool.Put(*in)
	}
	in.ManualSliceField.Reset()
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructEverything) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructEverything{}
	StructEverythingPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructExplicitObject) DeepCopyInto(out *StructExplicitObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructExplicitObject.
func (in *StructExplicitObject) DeepCopy() *StructExplicitObject {
	if in == nil {
		return nil
	}
	out := StructExplicitObjectPool.Get().(*StructExplicitObject)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructExplicitObject) Reset() {
	if in == nil {
		return
	}
	*in = StructExplicitObject{}
	StructExplicitObjectPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructExplicitObject) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructExplicitObject) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructExplicitObject{}
	StructExplicitObjectPool.Put(in)
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructExplicitObject) DeepCopyObject() otherpkg.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ResetObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructExplicitObject) ResetObject() {
	in.Reset()
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructExplicitSelectorExplicitObject) DeepCopyInto(out *StructExplicitSelectorExplicitObject) {
	*out = *in
	out.StructTypeMeta = in.StructTypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructExplicitSelectorExplicitObject.
func (in *StructExplicitSelectorExplicitObject) DeepCopy() *StructExplicitSelectorExplicitObject {
	if in == nil {
		return nil
	}
	out := StructExplicitSelectorExplicitObjectPool.Get().(*StructExplicitSelectorExplicitObject)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructExplicitSelectorExplicitObject) Reset() {
	if in == nil {
		return
	}
	*in = StructExplicitSelectorExplicitObject{}
	StructExplicitSelectorExplicitObjectPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructExplicitSelectorExplicitObject) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructExplicitSelectorExplicitObject) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructExplicitSelectorExplicitObject{}
	StructExplicitSelectorExplicitObjectPool.Put(in)
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructExplicitSelectorExplicitObject) DeepCopyObject() otherpkg.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopySelector is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *StructExplicitSelectorExplicitObject) DeepCopySelector() Selector {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ResetObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructExplicitSelectorExplicitObject) ResetObject() {
	in.Reset()
}

// ResetSelector is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *StructExplicitSelectorExplicitObject) ResetSelector() {
	in.Reset()
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructInterfaces) DeepCopyInto(out *StructInterfaces) {
	*out = *in
	if in.ObjectField != nil {
		out.ObjectField = in.ObjectField.DeepCopyObject()
	}
	if in.NilObjectField != nil {
		out.NilObjectField = in.NilObjectField.DeepCopyObject()
	}
	if in.SelectorField != nil {
		out.SelectorField = in.SelectorField.DeepCopySelector()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructInterfaces.
func (in *StructInterfaces) DeepCopy() *StructInterfaces {
	if in == nil {
		return nil
	}
	out := StructInterfacesPool.Get().(*StructInterfaces)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructInterfaces) Reset() {
	if in == nil {
		return
	}
	if in.ObjectField != nil {
		in.ObjectField.ResetObject()
	}
	if in.NilObjectField != nil {
		in.NilObjectField.ResetObject()
	}
	if in.SelectorField != nil {
		in.SelectorField.ResetSelector()
	}
	*in = StructInterfaces{}
	StructInterfacesPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructInterfaces) ResetNoSelf() {
	if in == nil {
		return
	}
	if in.ObjectField != nil {
		in.ObjectField.ResetObject()
	}
	if in.NilObjectField != nil {
		in.NilObjectField.ResetObject()
	}
	if in.SelectorField != nil {
		in.SelectorField.ResetSelector()
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructInterfaces) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructInterfaces{}
	StructInterfacesPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructNonPointerExplicitObject) DeepCopyInto(out *StructNonPointerExplicitObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructNonPointerExplicitObject.
func (in *StructNonPointerExplicitObject) DeepCopy() *StructNonPointerExplicitObject {
	if in == nil {
		return nil
	}
	out := StructNonPointerExplicitObjectPool.Get().(*StructNonPointerExplicitObject)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructNonPointerExplicitObject) Reset() {
	if in == nil {
		return
	}
	*in = StructNonPointerExplicitObject{}
	StructNonPointerExplicitObjectPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructNonPointerExplicitObject) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructNonPointerExplicitObject) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructNonPointerExplicitObject{}
	StructNonPointerExplicitObjectPool.Put(in)
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in StructNonPointerExplicitObject) DeepCopyObject() otherpkg.Object {
	return *in.DeepCopy()
}

// ResetObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in StructNonPointerExplicitObject) ResetObject() {
	in.Reset()
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructObjectAndList) DeepCopyInto(out *StructObjectAndList) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructObjectAndList.
func (in *StructObjectAndList) DeepCopy() *StructObjectAndList {
	if in == nil {
		return nil
	}
	out := StructObjectAndListPool.Get().(*StructObjectAndList)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructObjectAndList) Reset() {
	if in == nil {
		return
	}
	*in = StructObjectAndList{}
	StructObjectAndListPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructObjectAndList) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructObjectAndList) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructObjectAndList{}
	StructObjectAndListPool.Put(in)
}

// DeepCopyList is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.List.
func (in *StructObjectAndList) DeepCopyList() otherpkg.List {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructObjectAndList) DeepCopyObject() otherpkg.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ResetList is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.List.
func (in *StructObjectAndList) ResetList() {
	in.Reset()
}

// ResetObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructObjectAndList) ResetObject() {
	in.Reset()
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructObjectAndObject) DeepCopyInto(out *StructObjectAndObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructObjectAndObject.
func (in *StructObjectAndObject) DeepCopy() *StructObjectAndObject {
	if in == nil {
		return nil
	}
	out := StructObjectAndObjectPool.Get().(*StructObjectAndObject)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructObjectAndObject) Reset() {
	if in == nil {
		return
	}
	*in = StructObjectAndObject{}
	StructObjectAndObjectPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructObjectAndObject) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructObjectAndObject) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructObjectAndObject{}
	StructObjectAndObjectPool.Put(in)
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructObjectAndObject) DeepCopyObject() otherpkg.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ResetObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructObjectAndObject) ResetObject() {
	in.Reset()
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructPrimitivePointers) DeepCopyInto(out *StructPrimitivePointers) {
	*out = *in
	if in.BoolPtrField != nil {
		in, out := &in.BoolPtrField, &out.BoolPtrField
		*out = boolp_Pool.Get().(*bool)
		**out = **in
	}
	if in.IntPtrField != nil {
		in, out := &in.IntPtrField, &out.IntPtrField
		*out = intp_Pool.Get().(*int)
		**out = **in
	}
	if in.StringPtrField != nil {
		in, out := &in.StringPtrField, &out.StringPtrField
		*out = stringp_Pool.Get().(*string)
		**out = **in
	}
	if in.FloatPtrField != nil {
		in, out := &in.FloatPtrField, &out.FloatPtrField
		*out = float64p_Pool.Get().(*float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructPrimitivePointers.
func (in *StructPrimitivePointers) DeepCopy() *StructPrimitivePointers {
	if in == nil {
		return nil
	}
	out := StructPrimitivePointersPool.Get().(*StructPrimitivePointers)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructPrimitivePointers) Reset() {
	if in == nil {
		return
	}
	if in.BoolPtrField != nil {
		in := &in.BoolPtrField
		x := (*bool)(*in)
		boolp_Pool.Put(x)
	}
	if in.IntPtrField != nil {
		in := &in.IntPtrField
		x := (*int)(*in)
		intp_Pool.Put(x)
	}
	if in.StringPtrField != nil {
		in := &in.StringPtrField
		x := (*string)(*in)
		stringp_Pool.Put(x)
	}
	if in.FloatPtrField != nil {
		in := &in.FloatPtrField
		x := (*float64)(*in)
		float64p_Pool.Put(x)
	}
	*in = StructPrimitivePointers{}
	StructPrimitivePointersPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructPrimitivePointers) ResetNoSelf() {
	if in == nil {
		return
	}
	if in.BoolPtrField != nil {
		in := &in.BoolPtrField
		x := (*bool)(*in)
		boolp_Pool.Put(x)
	}
	if in.IntPtrField != nil {
		in := &in.IntPtrField
		x := (*int)(*in)
		intp_Pool.Put(x)
	}
	if in.StringPtrField != nil {
		in := &in.StringPtrField
		x := (*string)(*in)
		stringp_Pool.Put(x)
	}
	if in.FloatPtrField != nil {
		in := &in.FloatPtrField
		x := (*float64)(*in)
		float64p_Pool.Put(x)
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructPrimitivePointers) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructPrimitivePointers{}
	StructPrimitivePointersPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructPrimitivePointersAlias) DeepCopyInto(out *StructPrimitivePointersAlias) {
	*out = *in
	if in.BoolPtrField != nil {
		in, out := &in.BoolPtrField, &out.BoolPtrField
		*out = boolp_Pool.Get().(*bool)
		**out = **in
	}
	if in.IntPtrField != nil {
		in, out := &in.IntPtrField, &out.IntPtrField
		*out = intp_Pool.Get().(*int)
		**out = **in
	}
	if in.StringPtrField != nil {
		in, out := &in.StringPtrField, &out.StringPtrField
		*out = stringp_Pool.Get().(*string)
		**out = **in
	}
	if in.FloatPtrField != nil {
		in, out := &in.FloatPtrField, &out.FloatPtrField
		*out = float64p_Pool.Get().(*float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructPrimitivePointersAlias.
func (in *StructPrimitivePointersAlias) DeepCopy() *StructPrimitivePointersAlias {
	if in == nil {
		return nil
	}
	out := StructPrimitivePointersAliasPool.Get().(*StructPrimitivePointersAlias)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructPrimitivePointersAlias) Reset() {
	if in == nil {
		return
	}
	if in.BoolPtrField != nil {
		in := &in.BoolPtrField
		x := (*bool)(*in)
		boolp_Pool.Put(x)
	}
	if in.IntPtrField != nil {
		in := &in.IntPtrField
		x := (*int)(*in)
		intp_Pool.Put(x)
	}
	if in.StringPtrField != nil {
		in := &in.StringPtrField
		x := (*string)(*in)
		stringp_Pool.Put(x)
	}
	if in.FloatPtrField != nil {
		in := &in.FloatPtrField
		x := (*float64)(*in)
		float64p_Pool.Put(x)
	}
	*in = StructPrimitivePointersAlias{}
	StructPrimitivePointersAliasPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructPrimitivePointersAlias) ResetNoSelf() {
	if in == nil {
		return
	}
	if in.BoolPtrField != nil {
		in := &in.BoolPtrField
		x := (*bool)(*in)
		boolp_Pool.Put(x)
	}
	if in.IntPtrField != nil {
		in := &in.IntPtrField
		x := (*int)(*in)
		intp_Pool.Put(x)
	}
	if in.StringPtrField != nil {
		in := &in.StringPtrField
		x := (*string)(*in)
		stringp_Pool.Put(x)
	}
	if in.FloatPtrField != nil {
		in := &in.FloatPtrField
		x := (*float64)(*in)
		float64p_Pool.Put(x)
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructPrimitivePointersAlias) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructPrimitivePointersAlias{}
	StructPrimitivePointersAliasPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructPrimitives) DeepCopyInto(out *StructPrimitives) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructPrimitives.
func (in *StructPrimitives) DeepCopy() *StructPrimitives {
	if in == nil {
		return nil
	}
	out := StructPrimitivesPool.Get().(*StructPrimitives)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructPrimitives) Reset() {
	if in == nil {
		return
	}
	*in = StructPrimitives{}
	StructPrimitivesPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructPrimitives) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructPrimitives) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructPrimitives{}
	StructPrimitivesPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructPrimitivesAlias) DeepCopyInto(out *StructPrimitivesAlias) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructPrimitivesAlias.
func (in *StructPrimitivesAlias) DeepCopy() *StructPrimitivesAlias {
	if in == nil {
		return nil
	}
	out := StructPrimitivesAliasPool.Get().(*StructPrimitivesAlias)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructPrimitivesAlias) Reset() {
	if in == nil {
		return
	}
	*in = StructPrimitivesAlias{}
	StructPrimitivesAliasPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructPrimitivesAlias) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructPrimitivesAlias) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructPrimitivesAlias{}
	StructPrimitivesAliasPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructSlices) DeepCopyInto(out *StructSlices) {
	*out = *in
	if in.SliceBoolField != nil {
		in, out := &in.SliceBoolField, &out.SliceBoolField
		*out = s_boolSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceByteField != nil {
		in, out := &in.SliceByteField, &out.SliceByteField
		*out = s_byteSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceIntField != nil {
		in, out := &in.SliceIntField, &out.SliceIntField
		*out = s_intSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStringField != nil {
		in, out := &in.SliceStringField, &out.SliceStringField
		*out = s_stringSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceFloatField != nil {
		in, out := &in.SliceFloatField, &out.SliceFloatField
		*out = s_float64SPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStructPrimitivesField != nil {
		in, out := &in.SliceStructPrimitivesField, &out.SliceStructPrimitivesField
		*out = s_StructPrimitivesSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStructPrimitivesAliasField != nil {
		in, out := &in.SliceStructPrimitivesAliasField, &out.SliceStructPrimitivesAliasField
		*out = s_StructPrimitivesAliasSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStructPrimitivePointersField != nil {
		in, out := &in.SliceStructPrimitivePointersField, &out.SliceStructPrimitivePointersField
		*out = s_StructPrimitivePointersSPool.Get(len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SliceStructPrimitivePointersAliasField != nil {
		in, out := &in.SliceStructPrimitivePointersAliasField, &out.SliceStructPrimitivePointersAliasField
		*out = s_StructPrimitivePointersAliasSPool.Get(len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SliceSliceIntField != nil {
		in, out := &in.SliceSliceIntField, &out.SliceSliceIntField
		*out = s_s_intSPool.Get(len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = s_intSPool.Get(len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.SliceManualStructField != nil {
		in, out := &in.SliceManualStructField, &out.SliceManualStructField
		*out = s_ManualStructSPool.Get(len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ManualSliceField = in.ManualSliceField.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructSlices.
func (in *StructSlices) DeepCopy() *StructSlices {
	if in == nil {
		return nil
	}
	out := StructSlicesPool.Get().(*StructSlices)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructSlices) Reset() {
	if in == nil {
		return
	}
	if in.SliceBoolField != nil {
		in := &in.SliceBoolField
		s_boolSPool.Put(*in)
	}
	if in.SliceByteField != nil {
		in := &in.SliceByteField
		s_byteSPool.Put(*in)
	}
	if in.SliceIntField != nil {
		in := &in.SliceIntField
		s_intSPool.Put(*in)
	}
	if in.SliceStringField != nil {
		in := &in.SliceStringField
		s_stringSPool.Put(*in)
	}
	if in.SliceFloatField != nil {
		in := &in.SliceFloatField
		s_float64SPool.Put(*in)
	}
	if in.SliceStructPrimitivesField != nil {
		in := &in.SliceStructPrimitivesField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivesSPool.Put(*in)
	}
	if in.SliceStructPrimitivesAliasField != nil {
		in := &in.SliceStructPrimitivesAliasField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivesAliasSPool.Put(*in)
	}
	if in.SliceStructPrimitivePointersField != nil {
		in := &in.SliceStructPrimitivePointersField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivePointersSPool.Put(*in)
	}
	if in.SliceStructPrimitivePointersAliasField != nil {
		in := &in.SliceStructPrimitivePointersAliasField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivePointersAliasSPool.Put(*in)
	}
	if in.SliceSliceIntField != nil {
		in := &in.SliceSliceIntField
		for i := range *in {
			if (*in)[i] != nil {
				in := &(*in)[i]
				s_intSPool.Put(*in)
			}
		}
		s_s_intSPool.Put(*in)
	}
	if in.SliceManualStructField != nil {
		in := &in.SliceManualStructField
		for i := range *in {
			(*in)[i].Reset()
		}
		s_ManualStructSPool.Put(*in)
	}
	in.ManualSliceField.Reset()
	*in = StructSlices{}
	StructSlicesPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructSlices) ResetNoSelf() {
	if in == nil {
		return
	}
	if in.SliceBoolField != nil {
		in := &in.SliceBoolField
		s_boolSPool.Put(*in)
	}
	if in.SliceByteField != nil {
		in := &in.SliceByteField
		s_byteSPool.Put(*in)
	}
	if in.SliceIntField != nil {
		in := &in.SliceIntField
		s_intSPool.Put(*in)
	}
	if in.SliceStringField != nil {
		in := &in.SliceStringField
		s_stringSPool.Put(*in)
	}
	if in.SliceFloatField != nil {
		in := &in.SliceFloatField
		s_float64SPool.Put(*in)
	}
	if in.SliceStructPrimitivesField != nil {
		in := &in.SliceStructPrimitivesField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivesSPool.Put(*in)
	}
	if in.SliceStructPrimitivesAliasField != nil {
		in := &in.SliceStructPrimitivesAliasField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivesAliasSPool.Put(*in)
	}
	if in.SliceStructPrimitivePointersField != nil {
		in := &in.SliceStructPrimitivePointersField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivePointersSPool.Put(*in)
	}
	if in.SliceStructPrimitivePointersAliasField != nil {
		in := &in.SliceStructPrimitivePointersAliasField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivePointersAliasSPool.Put(*in)
	}
	if in.SliceSliceIntField != nil {
		in := &in.SliceSliceIntField
		for i := range *in {
			if (*in)[i] != nil {
				in := &(*in)[i]
				s_intSPool.Put(*in)
			}
		}
		s_s_intSPool.Put(*in)
	}
	if in.SliceManualStructField != nil {
		in := &in.SliceManualStructField
		for i := range *in {
			(*in)[i].Reset()
		}
		s_ManualStructSPool.Put(*in)
	}
	in.ManualSliceField.Reset()
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructSlices) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructSlices{}
	StructSlicesPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructSlicesAlias) DeepCopyInto(out *StructSlicesAlias) {
	*out = *in
	if in.SliceBoolField != nil {
		in, out := &in.SliceBoolField, &out.SliceBoolField
		*out = s_boolSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceByteField != nil {
		in, out := &in.SliceByteField, &out.SliceByteField
		*out = s_byteSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceIntField != nil {
		in, out := &in.SliceIntField, &out.SliceIntField
		*out = s_intSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStringField != nil {
		in, out := &in.SliceStringField, &out.SliceStringField
		*out = s_stringSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceFloatField != nil {
		in, out := &in.SliceFloatField, &out.SliceFloatField
		*out = s_float64SPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStructPrimitivesField != nil {
		in, out := &in.SliceStructPrimitivesField, &out.SliceStructPrimitivesField
		*out = s_StructPrimitivesSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStructPrimitivesAliasField != nil {
		in, out := &in.SliceStructPrimitivesAliasField, &out.SliceStructPrimitivesAliasField
		*out = s_StructPrimitivesAliasSPool.Get(len(*in))
		copy(*out, *in)
	}
	if in.SliceStructPrimitivePointersField != nil {
		in, out := &in.SliceStructPrimitivePointersField, &out.SliceStructPrimitivePointersField
		*out = s_StructPrimitivePointersSPool.Get(len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SliceStructPrimitivePointersAliasField != nil {
		in, out := &in.SliceStructPrimitivePointersAliasField, &out.SliceStructPrimitivePointersAliasField
		*out = s_StructPrimitivePointersAliasSPool.Get(len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SliceSliceIntField != nil {
		in, out := &in.SliceSliceIntField, &out.SliceSliceIntField
		*out = s_s_intSPool.Get(len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = s_intSPool.Get(len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.SliceManualStructField != nil {
		in, out := &in.SliceManualStructField, &out.SliceManualStructField
		*out = s_ManualStructSPool.Get(len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ManualSliceField = in.ManualSliceField.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructSlicesAlias.
func (in *StructSlicesAlias) DeepCopy() *StructSlicesAlias {
	if in == nil {
		return nil
	}
	out := StructSlicesAliasPool.Get().(*StructSlicesAlias)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructSlicesAlias) Reset() {
	if in == nil {
		return
	}
	if in.SliceBoolField != nil {
		in := &in.SliceBoolField
		s_boolSPool.Put(*in)
	}
	if in.SliceByteField != nil {
		in := &in.SliceByteField
		s_byteSPool.Put(*in)
	}
	if in.SliceIntField != nil {
		in := &in.SliceIntField
		s_intSPool.Put(*in)
	}
	if in.SliceStringField != nil {
		in := &in.SliceStringField
		s_stringSPool.Put(*in)
	}
	if in.SliceFloatField != nil {
		in := &in.SliceFloatField
		s_float64SPool.Put(*in)
	}
	if in.SliceStructPrimitivesField != nil {
		in := &in.SliceStructPrimitivesField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivesSPool.Put(*in)
	}
	if in.SliceStructPrimitivesAliasField != nil {
		in := &in.SliceStructPrimitivesAliasField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivesAliasSPool.Put(*in)
	}
	if in.SliceStructPrimitivePointersField != nil {
		in := &in.SliceStructPrimitivePointersField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivePointersSPool.Put(*in)
	}
	if in.SliceStructPrimitivePointersAliasField != nil {
		in := &in.SliceStructPrimitivePointersAliasField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivePointersAliasSPool.Put(*in)
	}
	if in.SliceSliceIntField != nil {
		in := &in.SliceSliceIntField
		for i := range *in {
			if (*in)[i] != nil {
				in := &(*in)[i]
				s_intSPool.Put(*in)
			}
		}
		s_s_intSPool.Put(*in)
	}
	if in.SliceManualStructField != nil {
		in := &in.SliceManualStructField
		for i := range *in {
			(*in)[i].Reset()
		}
		s_ManualStructSPool.Put(*in)
	}
	in.ManualSliceField.Reset()
	*in = StructSlicesAlias{}
	StructSlicesAliasPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructSlicesAlias) ResetNoSelf() {
	if in == nil {
		return
	}
	if in.SliceBoolField != nil {
		in := &in.SliceBoolField
		s_boolSPool.Put(*in)
	}
	if in.SliceByteField != nil {
		in := &in.SliceByteField
		s_byteSPool.Put(*in)
	}
	if in.SliceIntField != nil {
		in := &in.SliceIntField
		s_intSPool.Put(*in)
	}
	if in.SliceStringField != nil {
		in := &in.SliceStringField
		s_stringSPool.Put(*in)
	}
	if in.SliceFloatField != nil {
		in := &in.SliceFloatField
		s_float64SPool.Put(*in)
	}
	if in.SliceStructPrimitivesField != nil {
		in := &in.SliceStructPrimitivesField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivesSPool.Put(*in)
	}
	if in.SliceStructPrimitivesAliasField != nil {
		in := &in.SliceStructPrimitivesAliasField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivesAliasSPool.Put(*in)
	}
	if in.SliceStructPrimitivePointersField != nil {
		in := &in.SliceStructPrimitivePointersField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivePointersSPool.Put(*in)
	}
	if in.SliceStructPrimitivePointersAliasField != nil {
		in := &in.SliceStructPrimitivePointersAliasField
		for i := range *in {
			(*in)[i].ResetNoSelf()
		}
		s_StructPrimitivePointersAliasSPool.Put(*in)
	}
	if in.SliceSliceIntField != nil {
		in := &in.SliceSliceIntField
		for i := range *in {
			if (*in)[i] != nil {
				in := &(*in)[i]
				s_intSPool.Put(*in)
			}
		}
		s_s_intSPool.Put(*in)
	}
	if in.SliceManualStructField != nil {
		in := &in.SliceManualStructField
		for i := range *in {
			(*in)[i].Reset()
		}
		s_ManualStructSPool.Put(*in)
	}
	in.ManualSliceField.Reset()
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructSlicesAlias) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructSlicesAlias{}
	StructSlicesAliasPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructStructPrimitivePointers) DeepCopyInto(out *StructStructPrimitivePointers) {
	*out = *in
	in.StructField.DeepCopyInto(&out.StructField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructStructPrimitivePointers.
func (in *StructStructPrimitivePointers) DeepCopy() *StructStructPrimitivePointers {
	if in == nil {
		return nil
	}
	out := StructStructPrimitivePointersPool.Get().(*StructStructPrimitivePointers)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructStructPrimitivePointers) Reset() {
	if in == nil {
		return
	}
	in.StructField.ResetNoSelf()
	*in = StructStructPrimitivePointers{}
	StructStructPrimitivePointersPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructStructPrimitivePointers) ResetNoSelf() {
	if in == nil {
		return
	}
	in.StructField.ResetNoSelf()
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructStructPrimitivePointers) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructStructPrimitivePointers{}
	StructStructPrimitivePointersPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructStructPrimitives) DeepCopyInto(out *StructStructPrimitives) {
	*out = *in
	out.StructField = in.StructField
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructStructPrimitives.
func (in *StructStructPrimitives) DeepCopy() *StructStructPrimitives {
	if in == nil {
		return nil
	}
	out := StructStructPrimitivesPool.Get().(*StructStructPrimitives)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructStructPrimitives) Reset() {
	if in == nil {
		return
	}
	*in = StructStructPrimitives{}
	StructStructPrimitivesPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructStructPrimitives) ResetNoSelf() {
	if in == nil {
		return
	}
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructStructPrimitives) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructStructPrimitives{}
	StructStructPrimitivesPool.Put(in)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructStructSlices) DeepCopyInto(out *StructStructSlices) {
	*out = *in
	in.StructField.DeepCopyInto(&out.StructField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructStructSlices.
func (in *StructStructSlices) DeepCopy() *StructStructSlices {
	if in == nil {
		return nil
	}
	out := StructStructSlicesPool.Get().(*StructStructSlices)
	in.DeepCopyInto(out)
	return out
}

// Reset puts the given value back into the pool.
func (in *StructStructSlices) Reset() {
	if in == nil {
		return
	}
	in.StructField.ResetNoSelf()
	*in = StructStructSlices{}
	StructStructSlicesPool.Put(in)
}

// ResetNoSelf puts the given field value back into the pool.
func (in *StructStructSlices) ResetNoSelf() {
	if in == nil {
		return
	}
	in.StructField.ResetNoSelf()
}

// ResetOnlySelf puts the given value back into the pool.
func (in *StructStructSlices) ResetOnlySelf() {
	if in == nil {
		return
	}
	*in = StructStructSlices{}
	StructStructSlicesPool.Put(in)
}

var boolp_Pool = sync.Pool{New: func() any { return new(bool) }}
var float64p_Pool = sync.Pool{New: func() any { return new(float64) }}
var ManualStructAliasp_Pool = sync.Pool{New: func() any { return new(ManualStructAlias) }}
var intp_Pool = sync.Pool{New: func() any { return new(int) }}
var stringp_Pool = sync.Pool{New: func() any { return new(string) }}
var ManualStructAliasPool = sync.Pool{New: func() any { return new(ManualStructAlias) }}
var StructBPool = sync.Pool{New: func() any { return new(StructB) }}
var StructEmbedIntPool = sync.Pool{New: func() any { return new(StructEmbedInt) }}
var StructEmbedManualStructPool = sync.Pool{New: func() any { return new(StructEmbedManualStruct) }}
var StructEmbedPointerPool = sync.Pool{New: func() any { return new(StructEmbedPointer) }}
var StructEmbedStructPrimitivePointersPool = sync.Pool{New: func() any { return new(StructEmbedStructPrimitivePointers) }}
var StructEmbedStructPrimitivesPool = sync.Pool{New: func() any { return new(StructEmbedStructPrimitives) }}
var StructEmbedStructSlicesPool = sync.Pool{New: func() any { return new(StructEmbedStructSlices) }}
var StructEmptyPool = sync.Pool{New: func() any { return new(StructEmpty) }}
var StructEverythingPool = sync.Pool{New: func() any { return new(StructEverything) }}
var StructExplicitObjectPool = sync.Pool{New: func() any { return new(StructExplicitObject) }}
var StructExplicitSelectorExplicitObjectPool = sync.Pool{New: func() any { return new(StructExplicitSelectorExplicitObject) }}
var StructInterfacesPool = sync.Pool{New: func() any { return new(StructInterfaces) }}
var StructNonPointerExplicitObjectPool = sync.Pool{New: func() any { return new(StructNonPointerExplicitObject) }}
var StructObjectAndListPool = sync.Pool{New: func() any { return new(StructObjectAndList) }}
var StructObjectAndObjectPool = sync.Pool{New: func() any { return new(StructObjectAndObject) }}
var StructPrimitivePointersPool = sync.Pool{New: func() any { return new(StructPrimitivePointers) }}
var StructPrimitivePointersAliasPool = sync.Pool{New: func() any { return new(StructPrimitivePointersAlias) }}
var StructPrimitivesPool = sync.Pool{New: func() any { return new(StructPrimitives) }}
var StructPrimitivesAliasPool = sync.Pool{New: func() any { return new(StructPrimitivesAlias) }}
var StructSlicesPool = sync.Pool{New: func() any { return new(StructSlices) }}
var StructSlicesAliasPool = sync.Pool{New: func() any { return new(StructSlicesAlias) }}
var StructStructPrimitivePointersPool = sync.Pool{New: func() any { return new(StructStructPrimitivePointers) }}
var StructStructPrimitivesPool = sync.Pool{New: func() any { return new(StructStructPrimitives) }}
var StructStructSlicesPool = sync.Pool{New: func() any { return new(StructStructSlices) }}
var s_s_intSPool = newSlicePool[[]int]()
var s_boolSPool = newSlicePool[bool]()
var s_byteSPool = newSlicePool[byte]()
var s_float64SPool = newSlicePool[float64]()
var s_ManualStructSPool = newSlicePool[ManualStruct]()
var s_StructPrimitivePointersSPool = newSlicePool[StructPrimitivePointers]()
var s_StructPrimitivePointersAliasSPool = newSlicePool[StructPrimitivePointersAlias]()
var s_StructPrimitivesSPool = newSlicePool[StructPrimitives]()
var s_StructPrimitivesAliasSPool = newSlicePool[StructPrimitivesAlias]()
var s_intSPool = newSlicePool[int]()
var s_stringSPool = newSlicePool[string]()

type slice struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

type slicePool[T any] struct {
	pools [32]sync.Pool
}

func newSlicePool[T any]() slicePool[T] {
	return slicePool[T]{}
}

func index(n uint32) uint32 {
	return uint32(bits.Len32(n - 1))
}

func (p *slicePool[T]) Get(size int) []T {
	c := size
	// Small memory allocation is too scattered. the reuse rate is relatively high, types start with len=16
	if c < 16 {
		c = 16
	}
	idx := index(uint32(c))
	if v := p.pools[idx].Get(); v != nil {
		bp := v.(unsafe.Pointer)
		x := (*int32)(bp)
		c := *x
		*x = 0
		s := &slice{
			Data: bp,
			Len:  size,
			Cap:  int(c),
		}
		return *(*[]T)(unsafe.Pointer(s))
	}
	return make([]T, size, 1<<idx)
}

func (p *slicePool[T]) Put(value []T) {
	c := cap(value)
	if c < 16 {
		return
	}
	idx := index(uint32(c))
	// []T not obtained by Get is placed in the Pool of the previous index
	if c != 1<<idx {
		idx--
	}
	clear(value)
	slice := (*slice)(unsafe.Pointer(&value))
	x := (*int32)(slice.Data)
	*x = int32(c)
	p.pools[idx].Put(slice.Data)
}
