//go:build !ignore_autogenerated_zerolog
// +build !ignore_autogenerated_zerolog

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ___go_build_github_com_ravinggo_tools_zerolog_gen. DO NOT EDIT.

package output

import (
	buffer "github.com/mailru/easyjson/buffer"
	jwriter "github.com/mailru/easyjson/jwriter"
	objectpool "github.com/ravinggo/objectpool"
	zerolog "github.com/ravinggo/zerolog"
)

func (m *Domain) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("output.Domain error", err.Error())
	} else {
		e.RawJSON("output.Domain", d)
	}
}

func (m *Fight) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("output.Fight error", err.Error())
	} else {
		e.RawJSON("output.Fight", d)
	}
}

func (m *History) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("output.History error", err.Error())
	} else {
		e.RawJSON("output.History", d)
	}
}

func (m *Item) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("output.Item error", err.Error())
	} else {
		e.RawJSON("output.Item", d)
	}
}

func (m *Player) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("output.Player error", err.Error())
	} else {
		e.RawJSON("output.Player", d)
	}
}

func (m *User) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("output.User error", err.Error())
	} else {
		e.RawJSON("output.User", d)
	}
}
