package structs

import (
	"sync"
	"time"
)

// +k8s:deepcopy-gen=false
type DateFields struct {
	CreateAt time.Time `json:"create_at" bson:"create_at"`
	UpdateAt time.Time `json:"update_at" bson:"update_at"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (this_ *DateFields) DeepCopyInto(out *DateFields) {
	*out = *this_
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DateFields.
func (this_ *DateFields) DeepCopy() *DateFields {
	if this_ == nil {
		return nil
	}
	out := DateFieldsPool.Get().(*DateFields)
	this_.DeepCopyInto(out)
	return out
}

func (this_ *DateFields) Reset() {
	*this_ = DateFields{}
	DateFieldsPool.Put(this_)
}

var DateFieldsPool = sync.Pool{New: func() interface{} { return &DateFields{} }}
